name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: jonasb/android-problem-matchers-action@v1
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: release
    - uses: actions/upload-artifact@v2
      with:
        name: Release
        path: 'release/*'

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: jonasb/android-problem-matchers-action@v1
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test --info
